set nocompatible
set history=50
set fenc=utf-8
filetype on

syntax on

set ruler
set number

set autoindent
set smartindent
set cindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

set showmatch
set matchtime=5
set hlsearch
set incsearch

set mouse=v

